version: '3.8'
services:
  backend:
    build:
      context: ./backend  
    container_name: laravel-app
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=fsd10_tango
      - DB_USERNAME=fsduser
      - DB_PASSWORD=myDBpw
      - LOG_CHANNEL=daily
      - LOG_LEVEL=debug
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - JWT_SECRET=
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html 
      - /var/www/html/vendor

  frontend:
    build:
      context: ./recipe-app  
    container_name: react-app
    ports:
      - "3000:3000"  
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_USE_MOCK_DATA=false
    volumes:
      - ./recipe-app:/app
      - /app/node_modules

  mysql:
    image: mysql:8.1.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: myDBpw
      MYSQL_USER: fsduser
      MYSQL_PASSWORD: myDBpw
      MYSQL_DATABASE: fsd10_tango
    ports:
      - "3307:3306"  

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

