version: '3.8'

services:

  # Laravel Service
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  # React Service
  client:
    build:
      context: .
      dockerfile: ./recipe-app/Dockerfile
    container_name: react-client
    volumes:
      - ./recipe-app/build:/usr/share/nginx/html
    ports:
      - '3000:80'
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: fsd10_tango
      MYSQL_USER: fsduser
      MYSQL_PASSWORD: myDBpw
      MYSQL_ROOT_PASSWORD: myDBpw
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

        # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    ports:
      - '8080:80'
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
